name: Update Time in README

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes
  workflow_dispatch:

jobs:
  update-time:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: 'hh:mm:ss A dddd DD MMMM YYYY'
          timezone: 'Asia/Kathmandu'

      - name: Update README with current time
        run: |
          TIME="${{ steps.current-time.outputs.formattedTime }}"
          DATETIME="${{ steps.current-time.outputs.time }}"
          sed -i "s|<!-- TIME -->|<!-- TIME -->\n<time datetime=\"$DATETIME\">$TIME</time>|" README.md

      - name: Check for changes
        id: changed
        run: |
          git diff --quiet || echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Commit and push changes
        if: steps.changed.outputs.changed == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git fetch origin main
          git stash push -m "temp changes"
          git checkout main
          git rebase origin/main
          git stash pop
          git add .
          git commit -m "Update time to $TIME"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
