name: Update Time in README

on:
  schedule:
    - cron: '*/5 * * * *'       # GitHub only allows minimum 5 min interval :contentReference[oaicite:1]{index=1}
  workflow_dispatch:

jobs:
  update-time:
    permissions:
      contents: write           # ensures GITHUB_TOKEN can push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: 'hh:mm:ss A dddd DD MMMM YYYY'
          timezone: 'Asia/Kathmandu'

      - name: Update README with current time
        run: |
          TIME="${{ steps.current-time.outputs.formattedTime }}"
          DATETIME="${{ steps.current-time.outputs.time }}"
          sed -i "s|<!-- TIME -->|<!-- TIME -->\n<time datetime=\"$DATETIME\">$TIME</time>|" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git commit -m "Update time to $TIME" || echo "No changes to commit"
          git pull --rebase origin main   # sync to avoid fast-forward issues :contentReference[oaicite:2]{index=2}
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
