name: Update Time in README

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  update-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time
        with:
          format: 'hh:mm:ss A dddd DD MMMM YYYY' # Custom format for "09:54:34 PM Thursday 19 June 2025"

      - name: Update README with current time
        run: |
          TIME="${{ steps.current-time.outputs.time }}"
          sed -i "s|<!-- TIME -->|<!-- TIME -->\n<time datetime=\"$(date -u '+%Y-%m-%dT%H:%M:%SZ')\">$TIME</time>|" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git commit -m "Update time to $TIME" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
